package com.clover.spika.enterprise.chat.models;

import java.util.List;
import com.clover.spika.enterprise.chat.models.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LIST_USER_DETAILS.
 */
public class ListUserDetails implements java.io.Serializable {

    private Long id;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ListUserDetailsDao myDao;

    private List<MapKeyValueUserDetails> mapKeyValueUserDetailsList;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ListUserDetails() {
    }

    public ListUserDetails(Long id) {
        this.id = id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getListUserDetailsDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<MapKeyValueUserDetails> getMapKeyValueUserDetailsList() {
        if (mapKeyValueUserDetailsList == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            MapKeyValueUserDetailsDao targetDao = daoSession.getMapKeyValueUserDetailsDao();
            List<MapKeyValueUserDetails> mapKeyValueUserDetailsListNew = targetDao._queryListUserDetails_MapKeyValueUserDetailsList(id);
            synchronized (this) {
                if(mapKeyValueUserDetailsList == null) {
                    mapKeyValueUserDetailsList = mapKeyValueUserDetailsListNew;
                }
            }
        }
        return mapKeyValueUserDetailsList;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetMapKeyValueUserDetailsList() {
        mapKeyValueUserDetailsList = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
