package com.medicbleep.app.chat.models.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table GROUPS.
 */
public class Groups {

    private long id;
    private String type;
    private String groupname;
    private String image;
    private String image_thumb;
    private Integer is_member;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Groups() {
    }

    public Groups(long id) {
        this.id = id;
    }

    public Groups(long id, String type, String groupname, String image, String image_thumb, Integer is_member) {
        this.id = id;
        this.type = type;
        this.groupname = groupname;
        this.image = image;
        this.image_thumb = image_thumb;
        this.is_member = is_member;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getGroupname() {
        return groupname;
    }

    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getImage_thumb() {
        return image_thumb;
    }

    public void setImage_thumb(String image_thumb) {
        this.image_thumb = image_thumb;
    }

    public Integer getIs_member() {
        return is_member;
    }

    public void setIs_member(Integer is_member) {
        this.is_member = is_member;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
