package com.medicbleep.app.chat.models.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table USER_DETAILS.
 */
public class UserDetails {

    private Long id;
    private long user_id;
    private String key;
    private String label;
    private Integer keyboard_type;
    private String value;
    private Integer public_value;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserDetails() {
    }

    public UserDetails(Long id) {
        this.id = id;
    }

    public UserDetails(Long id, long user_id, String key, String label, Integer keyboard_type, String value, Integer public_value) {
        this.id = id;
        this.user_id = user_id;
        this.key = key;
        this.label = label;
        this.keyboard_type = keyboard_type;
        this.value = value;
        this.public_value = public_value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getUser_id() {
        return user_id;
    }

    public void setUser_id(long user_id) {
        this.user_id = user_id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Integer getKeyboard_type() {
        return keyboard_type;
    }

    public void setKeyboard_type(Integer keyboard_type) {
        this.keyboard_type = keyboard_type;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Integer getPublic_value() {
        return public_value;
    }

    public void setPublic_value(Integer public_value) {
        this.public_value = public_value;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
