package com.clover.spika.enterprise.chat.models.greendao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.clover.spika.enterprise.chat.models.greendao.CategoryDao;
import com.clover.spika.enterprise.chat.models.greendao.GroupDao;
import com.clover.spika.enterprise.chat.models.greendao.OrganizationDao;
import com.clover.spika.enterprise.chat.models.greendao.ListUserDetailsDao;
import com.clover.spika.enterprise.chat.models.greendao.MapKeyValueUserDetailsDao;
import com.clover.spika.enterprise.chat.models.greendao.UserDao;
import com.clover.spika.enterprise.chat.models.greendao.MessageDao;
import com.clover.spika.enterprise.chat.models.greendao.ChatDao;
import com.clover.spika.enterprise.chat.models.greendao.StickersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 32): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 32;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        CategoryDao.createTable(db, ifNotExists);
        GroupDao.createTable(db, ifNotExists);
        OrganizationDao.createTable(db, ifNotExists);
        ListUserDetailsDao.createTable(db, ifNotExists);
        MapKeyValueUserDetailsDao.createTable(db, ifNotExists);
        UserDao.createTable(db, ifNotExists);
        MessageDao.createTable(db, ifNotExists);
        ChatDao.createTable(db, ifNotExists);
        StickersDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        CategoryDao.dropTable(db, ifExists);
        GroupDao.dropTable(db, ifExists);
        OrganizationDao.dropTable(db, ifExists);
        ListUserDetailsDao.dropTable(db, ifExists);
        MapKeyValueUserDetailsDao.dropTable(db, ifExists);
        UserDao.dropTable(db, ifExists);
        MessageDao.dropTable(db, ifExists);
        ChatDao.dropTable(db, ifExists);
        StickersDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(CategoryDao.class);
        registerDaoClass(GroupDao.class);
        registerDaoClass(OrganizationDao.class);
        registerDaoClass(ListUserDetailsDao.class);
        registerDaoClass(MapKeyValueUserDetailsDao.class);
        registerDaoClass(UserDao.class);
        registerDaoClass(MessageDao.class);
        registerDaoClass(ChatDao.class);
        registerDaoClass(StickersDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
