package com.clover.spika.enterprise.chat.models.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.clover.spika.enterprise.chat.models.greendao.Category;
import com.clover.spika.enterprise.chat.models.greendao.Groups;
import com.clover.spika.enterprise.chat.models.greendao.Organization;
import com.clover.spika.enterprise.chat.models.greendao.ListUserDetails;
import com.clover.spika.enterprise.chat.models.greendao.MapKeyValueUserDetails;
import com.clover.spika.enterprise.chat.models.greendao.User;
import com.clover.spika.enterprise.chat.models.greendao.Message;
import com.clover.spika.enterprise.chat.models.greendao.Chat;
import com.clover.spika.enterprise.chat.models.greendao.Stickers;

import com.clover.spika.enterprise.chat.models.greendao.CategoryDao;
import com.clover.spika.enterprise.chat.models.greendao.GroupsDao;
import com.clover.spika.enterprise.chat.models.greendao.OrganizationDao;
import com.clover.spika.enterprise.chat.models.greendao.ListUserDetailsDao;
import com.clover.spika.enterprise.chat.models.greendao.MapKeyValueUserDetailsDao;
import com.clover.spika.enterprise.chat.models.greendao.UserDao;
import com.clover.spika.enterprise.chat.models.greendao.MessageDao;
import com.clover.spika.enterprise.chat.models.greendao.ChatDao;
import com.clover.spika.enterprise.chat.models.greendao.StickersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig groupsDaoConfig;
    private final DaoConfig organizationDaoConfig;
    private final DaoConfig listUserDetailsDaoConfig;
    private final DaoConfig mapKeyValueUserDetailsDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig chatDaoConfig;
    private final DaoConfig stickersDaoConfig;

    private final CategoryDao categoryDao;
    private final GroupsDao groupsDao;
    private final OrganizationDao organizationDao;
    private final ListUserDetailsDao listUserDetailsDao;
    private final MapKeyValueUserDetailsDao mapKeyValueUserDetailsDao;
    private final UserDao userDao;
    private final MessageDao messageDao;
    private final ChatDao chatDao;
    private final StickersDao stickersDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        groupsDaoConfig = daoConfigMap.get(GroupsDao.class).clone();
        groupsDaoConfig.initIdentityScope(type);

        organizationDaoConfig = daoConfigMap.get(OrganizationDao.class).clone();
        organizationDaoConfig.initIdentityScope(type);

        listUserDetailsDaoConfig = daoConfigMap.get(ListUserDetailsDao.class).clone();
        listUserDetailsDaoConfig.initIdentityScope(type);

        mapKeyValueUserDetailsDaoConfig = daoConfigMap.get(MapKeyValueUserDetailsDao.class).clone();
        mapKeyValueUserDetailsDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        chatDaoConfig = daoConfigMap.get(ChatDao.class).clone();
        chatDaoConfig.initIdentityScope(type);

        stickersDaoConfig = daoConfigMap.get(StickersDao.class).clone();
        stickersDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        groupsDao = new GroupsDao(groupsDaoConfig, this);
        organizationDao = new OrganizationDao(organizationDaoConfig, this);
        listUserDetailsDao = new ListUserDetailsDao(listUserDetailsDaoConfig, this);
        mapKeyValueUserDetailsDao = new MapKeyValueUserDetailsDao(mapKeyValueUserDetailsDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        chatDao = new ChatDao(chatDaoConfig, this);
        stickersDao = new StickersDao(stickersDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Groups.class, groupsDao);
        registerDao(Organization.class, organizationDao);
        registerDao(ListUserDetails.class, listUserDetailsDao);
        registerDao(MapKeyValueUserDetails.class, mapKeyValueUserDetailsDao);
        registerDao(User.class, userDao);
        registerDao(Message.class, messageDao);
        registerDao(Chat.class, chatDao);
        registerDao(Stickers.class, stickersDao);
    }
    
    public void clear() {
        categoryDaoConfig.getIdentityScope().clear();
        groupsDaoConfig.getIdentityScope().clear();
        organizationDaoConfig.getIdentityScope().clear();
        listUserDetailsDaoConfig.getIdentityScope().clear();
        mapKeyValueUserDetailsDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
        chatDaoConfig.getIdentityScope().clear();
        stickersDaoConfig.getIdentityScope().clear();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public GroupsDao getGroupsDao() {
        return groupsDao;
    }

    public OrganizationDao getOrganizationDao() {
        return organizationDao;
    }

    public ListUserDetailsDao getListUserDetailsDao() {
        return listUserDetailsDao;
    }

    public MapKeyValueUserDetailsDao getMapKeyValueUserDetailsDao() {
        return mapKeyValueUserDetailsDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public ChatDao getChatDao() {
        return chatDao;
    }

    public StickersDao getStickersDao() {
        return stickersDao;
    }

}
