package com.clover.spika.enterprise.chat.models.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.clover.spika.enterprise.chat.models.greendao.MapKeyValueUserDetails;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table MAP_KEY_VALUE_USER_DETAILS.
*/
public class MapKeyValueUserDetailsDao extends AbstractDao<MapKeyValueUserDetails, Long> {

    public static final String TABLENAME = "MAP_KEY_VALUE_USER_DETAILS";

    /**
     * Properties of entity MapKeyValueUserDetails.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Key = new Property(1, String.class, "key", false, "KEY");
        public final static Property Value = new Property(2, String.class, "value", false, "VALUE");
        public final static Property ListId = new Property(3, long.class, "listId", false, "LIST_ID");
    };

    private DaoSession daoSession;

    private Query<MapKeyValueUserDetails> listUserDetails_MapKeyValueUserDetailsListQuery;

    public MapKeyValueUserDetailsDao(DaoConfig config) {
        super(config);
    }
    
    public MapKeyValueUserDetailsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'MAP_KEY_VALUE_USER_DETAILS' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'KEY' TEXT," + // 1: key
                "'VALUE' TEXT," + // 2: value
                "'LIST_ID' INTEGER NOT NULL );"); // 3: listId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'MAP_KEY_VALUE_USER_DETAILS'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, MapKeyValueUserDetails entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String key = entity.getKey();
        if (key != null) {
            stmt.bindString(2, key);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(3, value);
        }
        stmt.bindLong(4, entity.getListId());
    }

    @Override
    protected void attachEntity(MapKeyValueUserDetails entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MapKeyValueUserDetails readEntity(Cursor cursor, int offset) {
        MapKeyValueUserDetails entity = new MapKeyValueUserDetails( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // key
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // value
            cursor.getLong(offset + 3) // listId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MapKeyValueUserDetails entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKey(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setValue(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setListId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(MapKeyValueUserDetails entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(MapKeyValueUserDetails entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "mapKeyValueUserDetailsList" to-many relationship of ListUserDetails. */
    public List<MapKeyValueUserDetails> _queryListUserDetails_MapKeyValueUserDetailsList(long listId) {
        synchronized (this) {
            if (listUserDetails_MapKeyValueUserDetailsListQuery == null) {
                QueryBuilder<MapKeyValueUserDetails> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ListId.eq(null));
                listUserDetails_MapKeyValueUserDetailsListQuery = queryBuilder.build();
            }
        }
        Query<MapKeyValueUserDetails> query = listUserDetails_MapKeyValueUserDetailsListQuery.forCurrentThread();
        query.setParameter(0, listId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getListUserDetailsDao().getAllColumns());
            builder.append(" FROM MAP_KEY_VALUE_USER_DETAILS T");
            builder.append(" LEFT JOIN LIST_USER_DETAILS T0 ON T.'LIST_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected MapKeyValueUserDetails loadCurrentDeep(Cursor cursor, boolean lock) {
        MapKeyValueUserDetails entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        ListUserDetails listUserDetails = loadCurrentOther(daoSession.getListUserDetailsDao(), cursor, offset);
         if(listUserDetails != null) {
            entity.setListUserDetails(listUserDetails);
        }

        return entity;    
    }

    public MapKeyValueUserDetails loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MapKeyValueUserDetails> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MapKeyValueUserDetails> list = new ArrayList<MapKeyValueUserDetails>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MapKeyValueUserDetails> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MapKeyValueUserDetails> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
