package com.clover.spika.enterprise.chat.models.greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table STICKERS.
 */
public class Stickers {

    private int id;
    private String filename;
    private Integer is_deleted;
    private Long created;
    private String url;
    private Integer organization_id;
    private Integer usedTimes;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Stickers() {
    }

    public Stickers(int id) {
        this.id = id;
    }

    public Stickers(int id, String filename, Integer is_deleted, Long created, String url, Integer organization_id, Integer usedTimes) {
        this.id = id;
        this.filename = filename;
        this.is_deleted = is_deleted;
        this.created = created;
        this.url = url;
        this.organization_id = organization_id;
        this.usedTimes = usedTimes;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    public Integer getIs_deleted() {
        return is_deleted;
    }

    public void setIs_deleted(Integer is_deleted) {
        this.is_deleted = is_deleted;
    }

    public Long getCreated() {
        return created;
    }

    public void setCreated(Long created) {
        this.created = created;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Integer getOrganization_id() {
        return organization_id;
    }

    public void setOrganization_id(Integer organization_id) {
        this.organization_id = organization_id;
    }

    public Integer getUsedTimes() {
        return usedTimes;
    }

    public void setUsedTimes(Integer usedTimes) {
        this.usedTimes = usedTimes;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
